In [1]:
import numpy as np

vector = np.array([2, 4, 4, 4, 5, 5, 7, 9])

mean=np.mean(vector)

variance = np.var(vector,ddof=1) # ddof=1 gives simple variance

# Output:
print(f'Array (1x{len(vector)} vector): {vector}')
print(f"Mean of the vector: {mean}")
print(f"Variance of the vector: {variance:.2f}")


# mean = 5.0
# variance = 4.57

Array (1x8 vector): [2 4 4 4 5 5 7 9]
Mean of the vector: 5.0
Variance of the vector: 4.57


In [2]:
import numpy as np

vector_x = np.array([2, 4, 6, 8, 10])
vector_y = np.array([1, 3, 5, 7, 9])

cov_matrix = np.cov(vector_x, vector_y, ddof=1)
covariance = cov_matrix[0, 1]

# Output
print(f"Covariance between vector_x and vector_y: {covariance:.2f}")

# covariance = 10.00

Covariance between vector_x and vector_y: 10.00


In [3]:
import numpy as np

N = 10
vector_x = np.array([10, 12, 18, 22, 29, 33, 37, 41, 25, 19])
vector_y = np.array([8, 11, 17, 23, 28, 32, 35, 39, 22, 16])

mean_x = np.mean(vector_x)
mean_y = np.mean(vector_y)

covariance = np.sum((vector_x - mean_x) * (vector_y - mean_y)) / (N - 1)

variance_x = np.var(vector_x, ddof=1)
variance_y = np.var(vector_y, ddof=1)

correlation = covariance / np.sqrt(variance_x * variance_y)

print(f'Vector X (1x{N} vector): {vector_x}')
print(f'Vector Y (1x{N} vector): {vector_y}')
print(f'Correlation: {correlation:.4f}')


Vector X (1x10 vector): [10 12 18 22 29 33 37 41 25 19]
Vector Y (1x10 vector): [ 8 11 17 23 28 32 35 39 22 16]
Correlation: 0.9935


In [4]:
import numpy as np

M = 4
N = 5

matrix = np.array([
    [1.2, 3.5, 5.7, 2.1, 4.4],
    [6.8, 2.4, 3.6, 8.7, 5.9],
    [4.3, 7.1, 8.2, 1.4, 3.7],
    [9.8, 2.1, 4.5, 6.2, 7.0]
])

matrix_T = matrix.T

covariance_matrix = np.cov(matrix_T, rowvar=False)

correlation_matrix = np.corrcoef(matrix_T, rowvar=False)

print(f'Matrix (MxN dimension):\n{matrix}\n')
print(f'Covariance Matrix (MxM dimension):\n{covariance_matrix}\n')
print(f'Correlation Matrix (MxM dimension):\n{correlation_matrix}\n')

Matrix (MxN dimension):
[[1.2 3.5 5.7 2.1 4.4]
 [6.8 2.4 3.6 8.7 5.9]
 [4.3 7.1 8.2 1.4 3.7]
 [9.8 2.1 4.5 6.2 7. ]]

Covariance Matrix (MxM dimension):
[[ 3.207  -2.8255  3.121  -2.867 ]
 [-2.8255  6.327  -6.3865  5.228 ]
 [ 3.121  -6.3865  7.443  -4.4235]
 [-2.867   5.228  -4.4235  8.227 ]]

Correlation Matrix (MxM dimension):
[[ 1.         -0.62725902  0.6388079  -0.5581584 ]
 [-0.62725902  1.         -0.93065773  0.72462934]
 [ 0.6388079  -0.93065773  1.         -0.56528996]
 [-0.5581584   0.72462934 -0.56528996  1.        ]]

